# Generated by Django 3.1 on 2020-08-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sounds_like',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
